source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '7.0'

pod 'AFNetworking'
pod 'HexColors'
pod 'Google-Maps-iOS-SDK'
pod 'SSKeychain'
pod 'geohash', :path => '../../c/geohash'
pod 'MBProgressHUD'
pod 'Mixpanel'
pod 'Facebook-iOS-SDK'
